com.auth0:java-jwt = 4.5.0
com.github.ben-manes.caffeine:caffeine = 3.2.2
com.fasterxml.jackson.*:* = 2.20.0
com.fasterxml.jackson.core:jackson-annotations = 2.20
com.google.errorprone:error_prone_core = 2.15.0
com.google.guava:guava = 33.5.0-jre
com.jakewharton.nopen:* = 1.0.1
com.markelliot.barista:* = 0.119.0
com.markelliot.barista.tracing:barista-tracing = 0.124.0
com.markelliot.result:result = 0.127.0
com.palantir.conjure:conjure = 4.22.0
com.palantir.conjure.java:* = 8.59.0
io.undertow:undertow-core = 2.3.20.Final
org.assertj:assertj-core = 3.27.6
org.junit:junit-bom = 6.0.0
org.junit.jupiter:junit-jupiter-engine = 6.0.0
