name: Deploy
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
    env:
      GRADLE_OPTS: -Dorg.gradle.console=plain
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build
        run: ./gradlew --no-daemon build docker
      - uses: superfly/flyctl-actions@1.1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
